[[end-notes]]
= End Notes

// TODO add text to introduce links

:dhammapada-url: https://forestsangha.org/teachings/books/a-dhammapada-for-contemplation?language=English

[[dhammapada-aruno]]
(1) *A Dhammapada For Contemplation*, Aruno Publications 2017, see link:{dhammapada-url}[online source].

[[ajahn-thate]]
(2) *Ajahn Thate* (1902-1994) was one of the most influential Thai Forest Tradition monks of the last century.

http://www.accesstoinsight.org/lib/thai/thate/thateauto.html

[[mahasaropama-sutta]]
(3) *Mahasaropama Sutta*

http://www.accesstoinsight.org/tipitaka/mn/mn.029.than.html

[[mahamangala-sutta]]
(4) *Mahamangala Sutta*

http://www.accesstoinsight.org/tipitaka/kn/snp/snp.2.04.nara.html

[[dhutanga]]
(5) *Dhutanga Vatta*

// TODO

*TAN GAMBHIRO CAN YOU KINDLY FILL IN THE 13*

[[faculties]]
(6) *Five spiritual faculties*

Saddha, Viriya, Sati, Samadhi, Pañña +
(Faith, Energy/Interest, Mindfulness, Concentration, Discernment)


// TODO

**TAN GAMBHIRO CAN YOU KINDLY FILL IN diacriticals**

[[hsu-yun]]
(7) *Master Hsu Yun* (1840-1959)

One of the most influential Chinese Buddhists of the last two centuries. See his
autobiography Empty Cloud. Died aged 119 years.

[[seeing-vol2]]
(8) *Seeing the Way, Volume 2*

https://forestsangha.org/teachings/books/seeing-the-way-vol-two?language=English

[[four-noble-truths]]
(9) *Four Noble Truths*

https://forestsangha.org/teachings/books/the-four-noble-truths?language=English

[[dhp-attahi]]
(10) *Attahi athano natho...*

TODO

[[inner-listening]]
(11) *Inner Listening*

For further details on using this meditation object, see Inner Listening by Ajahn Amaro:

https://forestsangha.org/teachings/books/inner-listening?language=English

[[dhp-276]]
(12) *Dhammapada verse 276*

// TODO verse formatting

The Awakened Ones can but point the way; we must make the effort ourselves.
Those who reflect wisely and enter the path are freed from the fetters of Mara.

[[gospel]]
(13) *The Gospel of Consumption*

https://orionmagazine.org/article/the-gospel-of-consumption/

[[right-effort]]
(14) *The Four Right Efforts*

- The effort to establish as yet unarisen wholesome states of mind.
- The effort to protect already arisen wholesome states of mind.
- The effort to remove already arisen unwholesome states of mind.
- The effort to avoid the arising of as yet unarisen unwholesome states of mind.

[[aj-sumedho-sound-of-silence]]
(15) *Ajahn Sumedho: Sound of Silence*

https://cdn.amaravati.org/wp-content/uploads/2014/10/Ajahn-Sumedho-Volume-4-The-Sound-of-Silence.pdf

[[wordly-dhammas]]
(16) *Eight Worldly Dhammas: Lokavipatti Sutta*

https://www.accesstoinsight.org/tipitaka/an/an08/an08.006.than.html

[[anapanasati]]
(17) *Mindfulness of Breathing Sutta*

https://www.accesstoinsight.org/tipitaka/mn/mn.118.than.html
