[[notes]]
= Notes

*[1]*[[dhammapada-aruno]] _A Dhammapada For Contemplation_, Aruno Publications, 2017

https://forestsangha.org/teachings/books/a-dhammapada-for-contemplation?language=English

*[2]*[[ajahn-thate]] _Ajahn Thate_ (1902-1994)

One of the most influential Thai Forest Tradition monks of the last century.

https://www.accesstoinsight.org/lib/thai/thate/thateauto.html

*[3]*[[mahasaropama-sutta]] _MN 29, Mahā-Sāropama Sutta: The Longer Heartwood-simile Discourse_

https://www.accesstoinsight.org/tipitaka/mn/mn.029.than.html

*[4]*[[mahamangala-sutta]] _Snp 2.4, Mahā-Maṅgala Sutta: Blessings_

https://www.accesstoinsight.org/tipitaka/kn/snp/snp.2.04.nara.html

*[5]*[[dhutanga]] _Dhutaṅga vaṭṭa_

Voluntary ascetic practices that practitioners may undertake from time to time
or as a long-term commitment in order to cultivate renunciation and
contentment, and to stir up energy. For the monks, there are thirteen such
practices: (1) using only patched-up robes; (2) using only one set of three
robes; (3) going for alms; (4) not by-passing any donors on one’s alms path;
(5) eating no more than one meal a day; (6) eating only from the alms-bowl;
(7) refusing any food offered after the almsround; (8) living in the forest;
(9) living under a tree; (10) living under the open sky; (11) living in a
cemetery; (12) being content with whatever dwelling one has; (13) not lying
down.

*[6]*[[faculties]] _Five spiritual faculties_

_Saddhā_ (faith, conviction), _viriya_ (persistence, energy, interest),
_sati_ (mindfulness), _samādhi_ (concentration), and _paññā_ (discernment).

*[7]*[[hsu-yun]] _Master Hsu Yun_ (1840-1959)

One of the most influential Chinese Buddhists of the last two centuries. See
his autobiography Empty Cloud. Died aged 119 years.

*[8]*[[seeing-vol2]] _Seeing the Way, Volume 2_

https://forestsangha.org/teachings/books/seeing-the-way-vol-two?language=English

*[9]*[[four-noble-truths]] _The Four Noble Truths_ by Ajahn Sumedho

https://forestsangha.org/teachings/books/the-four-noble-truths?language=English

*[10]*[[dhp-attahi]] _Dhammapada verse 160, ‘Attā hi attano nātho...’_

Truly it is ourselves +
that we depend upon; +
how could we really +
depend upon another? +
When we reach the state +
of self-reliance +
we find a rare refuge.

*[11]*[[inner-listening]] _Inner Listening_ by Ajahn Amaro

https://forestsangha.org/teachings/books/inner-listening?language=English

*[12]*[[dhp-276]] _Dhammapada verse 276_

The Awakened Ones +
can but point the way; +
we must make the effort ourselves. +
Those who reflect wisely +
and enter the path are freed +
from the fetters of Mara.

*[13]*[[gospel]] _The Gospel of Consumption_

https://orionmagazine.org/article/the-gospel-of-consumption/

*[14]*[[right-effort]] _The Four Right Efforts_

- The effort to establish as yet unarisen wholesome states of mind.
- The effort to protect already arisen wholesome states of mind.
- The effort to remove already arisen unwholesome states of mind.
- The effort to avoid the arising of as yet unarisen unwholesome states of mind.

*[15]*[[aj-sumedho-sound-of-silence]] _The Sound of Silence_ by Ajahn Sumedho

https://forestsangha.org/teachings/books/anthology-vol-4-the-sound-of-silence?language=English

*[16]*[[worldly-dhammas]] _AN 8.6, Lokavipatti Sutta: The Failings of the World_

The Eight Worldly Dhammas are described as: gain and loss, status and
disgrace, praise and blame, pleasure and pain.

https://www.accesstoinsight.org/tipitaka/an/an08/an08.006.than.html

*[17]*[[anapanasati]] _MN 118, Ānāpānasati Sutta: Mindfulness of Breathing_

https://www.accesstoinsight.org/tipitaka/mn/mn.118.than.html
